# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '''
[╭───󰁔 ](bold cyan)$sudo$username@$hostname$directory$git_branch$git_status$python$nodejs$lua
[╰─](bold cyan)$character'''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[󰁔](bold green)' # The 'success_symbol'er segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold blue"

[hostname]
disabled = false
ssh_only = false
format = "[$ssh_symbol$hostname]($style) "
style = "white"

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
